- bower.json
Hi, thanks for creating this mixin! It worked perfectly for my needs. Just FYI, you mentioned in the readme that this was available on Bower, but it actually wasn't, so I went ahead and registered it for you. I hope that was okay, I just really needed to use it ASAP.
> Update version to 0.2.1 in bower.json

- index.js
Unless that comment is getting at something I misunderstood, the method that is required is `handleClickOutside`, not `onClickOutside`, right?
> Fix comment-doc for required component function

- README.md
- index.js
In reference to https://github.com/Pomax/react-onclickoutside/issues/9
> Ignore elements

- index.js
> getting React module depending on package strategy

- index.js
> Fixes bug with SVG use not having classList

- index.js
The error says function, so I think the condition should do it as well.
> Explicit check if handleClickOutside is a function

- index.js
> use stopImmediatePropagation instead of stopPropagation

- index.js
- package.json
rebased #38 by @martijnrusschen
> Support React 0.14

- index.js
> handle case when target DOM is detached

- decorator.js
- package.json
> Adding react v15 support

- README.md
This adds documentation for the behaviour described in issue #71.
> Update docs to address disable listener call in componentDidMount difference for HOCs

- .gitignore
- karma.conf.js
- package.json
- test.js
Addresses #74 
This sets up the test infrastructure with karma and mocha, and adds a few basic integration tests.
> Add basic tests

- index.js
> Bind instance to event handler

- index.js
> Add display name for React devtools

- index.js
Change `OnClickOustide` to `OnClickOutside`
> Spelling fix

- index.js
- test/test.js
Rebased https://github.com/Pomax/react-onclickoutside/pull/107, fixes #106
> Add enable/disableOnClickOutside prop. Fixes #106

- .eslintrc.json
- index.js
- package.json
- test/test.js
adds a `lint` task to the npm scripts section, which gets called as part of `npm test`
> Added eslint

- index.js
- package.json
- test/browser/testit.js
- test/test.js
> fallback to call handleClickOutside from props

- .eslintrc.json
- index.js
- package.json
- test/no-dom-test.js
https://github.com/Pomax/react-onclickoutside/issues/136
> Dont fail if rendering in an environment with no DOM

- package.json
fixes #129
```
$ npm pack
$ tar -xzvf react-onclickoutside-5.7.1.tgz
package/package.json
package/README.md
package/index.js
```
> exclude tests from npm package

- index.js
> fix excludeScrollbar not working for horizontal scroll bar

- test/test.js
Still aint sure how to approach this one - https://github.com/Pomax/react-onclickoutside/pull/170#discussion_r118043966
> Refactored test - counter gets reset in beforeEach hook

- package.json
- src/generateOutsideCheck.js
- src/index.js
- test/browser/test1.js
- test/browser/test2.js
- test/karma.conf.js
- test/no-dom-test.js
- test/setup-pre-commit-hook.js
- test/test.js
I know you dont like too much dependencies, but thought that those might actually help to improve overall dev experience.
> Configured prettier for the project

- .babelrc
- package.json
* Building only commonjs version of the package neccessary for tests
* Restored loose mode for babel transforms - providing more concise code
> Deps cleanup (#202)

- src/index.js
Related https://github.com/Pomax/react-onclickoutside/issues/168#issuecomment-323229502
> Tweaked logic about passive listeners

- README.md
I found lack of `import` keyword
> Fix missing import syntax

- package.json
- rollup.config.js
> Update react & react-dom peer-dep to support 17.x

- package-lock.json
- package.json
update peer-dependencies react/react-dom to ver.18
> update peer-dependencies react/react-dom to ver.18
