- index.js
Since every component that uses this mixin will add to the module state when it mounts, we end up leaking memory. We Remove the components and event handlers from their respective arrays when the components unmount to avoid this.
> clean up handlers to avoid leaking memory

- index.js
The 'this.getDOMNode()' is deprecated and has been replaced with 'React.findDOMNode()'.
This point is also a impeditive to use it with the ES6 component that already don't has the getDOMNode.
I did a CodePen in onder to test it at least manually:
http://codepen.io/willgm/pen/oXPaov
> using the updated way to get the dom node on react

- index.js
We will manually traverse up in the dom tree, so stop event bubbling up with `Event.stopPropagation()`
> fix event bubbling up

- index.js
Reverts Pomax/react-onclickoutside#36 based on https://github.com/Pomax/react-onclickoutside/issues/35#issuecomment-147157982 and https://github.com/Pomax/react-onclickoutside/issues/40
> Revert "use stopImmediatePropagation instead of stopPropagation"

- README.md
- decorator.js
I'm using [ES6 class React Components](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html) which means mixins aren't supported. I'd like to propose the following to enable such use. It uses the same implementation as the mixin except that the component is passed into the various functions rather than them being member functions of the component itself. This also lends itself toward some configuration when initially registering the component.
I'd like to add some documentation to the main readme etc., but I'm expecting some discussion around this and would like to confirm your interest in this solution before going there. 
Excellent work on the mixin by the way!
> OnClickOutside for use with ES6 classes

- index.js
This fix ensures that the document object is available before calling
methods on it. 
This allows using the React shallow renderer utilities with components that make use of this mixin.
> Fix React shallow renderer

- index.js
require breaks if it's given an object instead of string.
> root should be first argument to factory, not require

- index.js
Hi there. I couldn't get the decorator work in React 0.14.2 and tracked it down to root.document always evaluating to null. Not sure why "root" was included there as document is a global variable. This fixes it.
> remove root from global document

- README.md
The ReadMe had me believing that this library would support IE9. But IE9 [does not support classList](http://caniuse.com/#search=classList). I checked IE9 and I had been getting `Unable to get value of the property 'contains': object is null or undefined`. Thanks for recommending the polyfill I will check it out.
> readme update for accurate browser support

- README.md
- index.js
Addresses #37
This allows consumers to get rid of the `'ignore-react-onclickoutside'` magic string in app code and use `IGNORE_CLASS` as the source of truth instead.
> Allow specification of ignore class by prop

- index.js
Fixes #72
It turns out `this` is `document` in this context, not the component, which was causing the prop lookup to fail.  Not sure why this worked on my end before... sorry for the trouble @Pomax.
> Properly read outsideClickIgnoreClass from props

- index.js
does the same thing as before (not attaching handlers)
except it doesn't throw anymore if there is no document
> prevent undefined error if called server side

- index.js
Thanks for awesome project! Unfortunately I have found it quite hard to use, for a simple case: list with elements you can select/deselect.
As I'm using redux all the data are passed down as a prop and the component state should be change according to those props. 
With the current plugin state triggering OnClickOutside for multiple list elements was hard and required a lot of not DRY code. With this simple fix, the only thing user have to do is change `disableOnClickOutside` from `false` to `true`.
> Enable dynamic disableOnClickOutside

- index.js
Fixes #92 - Disable outside click listening when the HOC's disableOnClickOutside prop flips from false to true.
> Fix - properly disable outside click listening on props change

- index.js
if the state of a component changes based on the outside click we want the target area to receive the completed event before modifying state.
take an accordion menu component for example - if an area above the next target collapses, we want to wait until the event is complete so that the next item can expand as a result of state change.
> Update index.js to use click event and not mousedown

- index.js
Hello!
We were also experiencing the issues reported in #89. It looks like we can avoid that warning by providing the context to `handleClickOutside` in a way that `React` doesn't take issue with.
Tests output before and after:
Let me know if there are any changes required!
> Avoid `console.warn` via delegation, fixes #89

- index.js
- test/test.js
This commits reverts #102 (so there are console.warns) again, but the PR was broken (see test). So I believe the revert is the sensible thing todo.
> This reverts #102 with a test why it was broken

- README.md
- index.js
- test/test.js
Fixes #115.
The implementation maintains compatibility with the previous call convention (as demonstrated in the tests), so it should not break semver.
> Add support for config, allow users to specify onClickOutside handler

- index.js
- package.json
- test/.eslintrc.json
- test/karma.conf.js
- test/test.js
This was a bit more complex than anticipated, because I had to add babel to reproduce the issue, but this test will fail if the regression fixed by #125 comes back.
This also brings to the forefront the difference between components created by inheritance, and components created by createClass. ~~The re-binding will give an error on the latter. Not sure what a long term solution is.~~ This can be fixed by looking at the prototype of the element.
> add test for binding issues

- index.js
- test/test.js
Stateless components don't support refs, so this
uses the props from the wrapper component instead.
`isReactComponent` isn't documented, but seems to
work for both ES6 classes and components created
with `React.createClass`.
Fixes #127
> Remove ref for stateless components

- package.json
The object-assign dependency was not being used and can thus be safely removed.
> Remove unused dependency from package.json

- index.js
This PR addresses https://github.com/Pomax/react-onclickoutside/issues/130 by allowing an option to exclude the browser scrollbar from the click outside check.
The default behavior would be the same as current behavior.
> Add option to exclude scrollbar from outside check

- README.md
I went digging in the issues to find an example for ES6 React Classes. Thought I try to slip the example into the documentation.
> Adding ES6 Usage Example to Readme.md

- README.md
- index.js
I added the ability to use `excludeScrollbar` for every instance of the wrapper component, using an option in the already existing `config` object that can be passed as second parameter to the `onClickOutside()` wrapper.
This is an opt-in that do not change the current behavior, and that can still be overriden by setting the `excludeScrollbar` prop per-instance as usual.
Implementation is quite neat: I simply used `getDefaultProps()` to set the `excludeScrollbar` prop, so the the feature is still working exactly as it was before.
> excludeScrollbar can now be set as default for every component instance

- README.md
- index.js
- test/no-dom-test.js
- test/test.js
I think we should migrate to the es6 `class` syntax and stop using `React.createClass`, but that would be another step. For now just created this PR, so people stop having deprecation warnings after migration to React v15.5. 
If you feel the same about `class`, I'll create an issue about it, so the matter won't get forgotten and neglected.
> Migrated deprecated React.createClass

- package.json
`jsnext:main` is kinda legacy now, and the `module` entry is the preffered one (previous one kept only for compatibility reasons)
I've pushed this only for parity, but keeping those entries is quite obsolete for [those reasons](https://github.com/Pomax/react-onclickoutside/issues/185#issuecomment-304054039)
> Added preferred module entry to the package.json

- README.md
Very minor change but I believe this will greatly improve readability
> Make HOC acronym declaration obvious

- package.json
this can be used when the package is used as git dependency
In theory now there shouldnt be any problem with this, as `build` is hooked as part of the `precommit`, but anyway I think that's useful if somebody forks and changes something or if `build` stops being part of the `precommit` at some point of the time in the future.
> Added prepare script, which can be used by npm5

- src/index.js
Adds the `WrappedComponent` display name to the error messages for easier debugging.
Manual test
- remove/add the `handleClickOutside` WrappedComponent handler and see if the error includes the `displayName`
> Add component name to errors

- src/index.js
Fix for the problem where the event handler was being called even though it was registered after the event was created
[](
https://github.com/Pomax/react-onclickoutside/issues/395)
> Compatibility Issues Between "React" and "React-OnClickOutside" Libraries
